// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfCuhSatxAxjqEbdR-Pv5LO94jSvkX71U',
    appId: '1:708345708542:web:a66b1fccc867ef5b694aaf',
    messagingSenderId: '708345708542',
    projectId: 'f-login-4fa01',
    authDomain: 'f-login-4fa01.firebaseapp.com',
    storageBucket: 'f-login-4fa01.appspot.com',
    measurementId: 'G-YCP8F69CKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC11qAFQEWtm2_NxOBc0fOlZWwTAisiCGE',
    appId: '1:708345708542:android:aa51638a451717cb694aaf',
    messagingSenderId: '708345708542',
    projectId: 'f-login-4fa01',
    storageBucket: 'f-login-4fa01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN0ZZ2rzDY4twbJSfkA04U_MdcxVgkhHM',
    appId: '1:708345708542:ios:dbb3a31b8e869a89694aaf',
    messagingSenderId: '708345708542',
    projectId: 'f-login-4fa01',
    storageBucket: 'f-login-4fa01.appspot.com',
    iosClientId: '708345708542-5n7pjb48j3k3aqvpns2bs6u9s4vdnk36.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN0ZZ2rzDY4twbJSfkA04U_MdcxVgkhHM',
    appId: '1:708345708542:ios:dbb3a31b8e869a89694aaf',
    messagingSenderId: '708345708542',
    projectId: 'f-login-4fa01',
    storageBucket: 'f-login-4fa01.appspot.com',
    iosClientId: '708345708542-5n7pjb48j3k3aqvpns2bs6u9s4vdnk36.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLogin',
  );
}
